---

- name: Install the inadyn package in CentOS 8
  yum: name=http://public.handverdrahtet.org/files/inadyn-mt-2.28.10-4.el8.x86_64.rpm state=present
  tags: [ 'package', 'inadyn' ]

- name: Include config
  import_tasks: "config.yml"
  tags: [ 'configuration', 'inadyn' ]

- name: Start inadyn service
  service: name=inadyn state=started enabled=yes
  tags: [ 'service', 'inadyn' ]

