---
- name: Add the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/default.yml"
  tags: [ 'configuration', 'package', 'service', 'inadyn' ]

- name: Add the OS specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags: [ 'configuration', 'package', 'service', 'inadyn' ]
