---

- name: Install the inadyn packages in Redhat derivatives
  yum: name=http://public.handverdrahtet.org/files/inadyn-mt-2.24.44-1.el7.centos.x86_64.rpm state=present
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'inadyn' ]

- name: Install the inadyn packages in Debian derivatives
  apt: name=inadyn state=present
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'inadyn' ]

- name: Configure inadyn-mt
  template: src=inadyn-mt.conf.j2 dest=/etc/inadyn-mt.conf
  notify:
  - restart inadyn
  tags: [ 'configuration', 'package', 'inadyn' ]

- name: Start/stop inadyn service
  service: name=inadyn state=started enabled=yes
  tags: [ 'service', 'inadyn' ]
