---
- name: Add the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "default.yml"
  tags: [ 'configuration', 'package', 'service', 'inadyn' ]

- name: Install the inadyn packages in Redhat derivatives
  yum: name=http://public.handverdrahtet.org/files/inadyn-mt-2.24.44-1.el7.centos.x86_64.rpm state=present
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'inadyn' ]

- name: Install the inadyn packages in Debian derivatives
  apt: name=inadyn state=present
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'inadyn' ]

- name: Configure inadyn
  template: src=inadyn-mt.conf.j2 dest={{ inadyn_config_file }}
  notify:
  - restart inadyn
  tags: [ 'configuration', 'package', 'inadyn' ]

- name: Enable inadyn service in Debian distribution
  lineinfile: dest=/etc/default/inadyn state=present regexp=^RUN_DAEMON line=RUN_DAEMON="yes"
  lineinfile: dest=/etc/default/inadyn state=present regexp=^RUN_IPUP   line=RUN_IPUP="no"
  when: ansible_distribution == 'Debian'
  tags: [ 'configuration', 'service', 'inadyn' ]

- name: Start inadyn service
  service: name=inadyn state=started enabled=yes
  when: not( ansible_distribution=='Ubuntu' and ansible_distribution_major_version=='12' )
  tags: [ 'service', 'inadyn' ]

- name: Start inadyn service (Ubuntu 12)
  cron: name="inadyn service" job="/usr/sbin/inadyn" special_time="reboot"
  when: ( ansible_distribution=='Ubuntu' and ansible_distribution_major_version=='12' )
  tags: [ 'service', 'inadyn' ]
